[build-system]
build-backend = "hatchling.build"
requires = [ "hatchling" ]

[project]
name = "fast-csv-loader"
version = "2.2.2"
description = "A fast and memory efficient way to load large CSV files (Timeseries data) into Pandas"
readme = "README.md"
keywords = [ "csv-loader", "csv-reader", "memory-efficient", "pandas-dataframe", "python3" ]
authors = [
  { name = "Benny Thadikaran" },
]
requires-python = ">=3.8"
classifiers = [
  "Intended Audience :: Developers",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [ "pandas>=2,<3" ]
optional-dependencies.docs = [ "furo==2024.8.6", "sphinx==8.1.3" ]
urls."Bug Tracker" = "https://github.com/BennyThadikaran/fast_csv_loader/issues"
urls.Homepage = "https://github.com/BennyThadikaran/fast_csv_loader"

[tool.hatch]
build.targets.wheel.exclude = [ ".github", "docs", "tests" ]
build.targets.sdist.exclude = [ ".github", "docs", "tests" ]
